
<network-architecture>	::= <pre-features> <pre-classification> (<softmax>) (<learning>)

<pre-features>			::= (<features>) (<features>)
						  | (<features>) (<features>) (<features>)
						  | (<features>) (<features>) (<features>) (<features>)
						  | (<features>) (<features>) (<features>) (<features>) (<features>)
						  | (<features>)

<features>				::= <convolution>
						  | <pooling>

<convolution> 			::= layer:conv num-filters:<num-filters> filter-shape:<filter-shape> stride:<stride> padding:same act:relu bias:True <batch-normalisation> merge-input:False

<num-filters>			::= 10|20|32|50|5
<filter-shape>			::= 1|3|5
<stride>				::= 1|2|3
<boolean>				::= True|False

<batch-normalisation> 	::= batch-normalisation:<boolean>

<pooling> 				::= <pool-type> kernel-size:1 stride:<stride> padding:same
<pool-type> 			::= layer:pool-max

<pre-classification> 	::= (<classification>)
						  | (<classification>) (<classification>)
<classification> 		::= <fully-connected>
<fully-connected> 		::= layer:fc act:relu num-units:<num-units> bias:True

<num-units>				::= 128|512|256

<softmax> 				::= layer:fc act:softmax num-units:2 bias:True
<learning> 				::= learning:adam learning-rate:<learning-rate>
<learning-rate>			::= 0.00001|0.0001|0.001|0.005
